- name: Test install nginx
  hosts: all
  become: true
  tasks:
    - name: "show ansible facts: "
      debug:
        var: ansible_facts['distribution']
    - name: Uninstall Nginx on Ubuntu by apt-get command
      block:
        - name: uninstall nginx on ubuntu
          shell: apt-get purge nginx nginx-common -y
          register: ubuntuerr1
        - name: Debug ubuntu
          debug:
            var: ubuntuerr1
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: install nginx on CentOS
      block:
      - name: install EPEL repo on CentOS
        yum: name=epel-release state=present
      - name: Install Nginx on Centos
        yum: name=nginx update_cache=yes state=latest
        register: err
      when: ansible_facts['distribution'] == "CentOS"
    - name: start server nginx
      service: name=nginx state=started enabled=yes

