- name: Test variable
  hosts: webserver, redhat
  gather_facts: true

  tasks:
    - name: "Show NTP info:"
      debug:
        #msg: "Target system (Web server) IP= {{inventory_hostname}} "
        var: ntp_server['IP'], httpd_port[1], mysql_port

    - name: Check uptime target server
      shell: uptime
      register: output
    - name: "show uptime from shell"
      debug:
        var: output

  vars:
    ntp_server: 
      IP: 192.168.1.1
      ntp_port: "UDP 123"
    http_port:
      - 80
      - 443
  vars_files:
    - ./vars/dbserver

